{
 "title": "Open CO2 Sensor",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CO2 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rco2{job=\"airgradient-livingroom\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atmp{job=\"airgradient-livingroom\"}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rhum{job=\"airgradient-livingroom\"}"
    }
   ]
  },
  {
   "title": "CO2 Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "rco2{job=\"airgradient-livingroom\"}",
     "legendFormat": "CO2"
    }
   ]
  },
  {
   "title": "Temperature/Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "atmp{job=\"airgradient-livingroom\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "rhum{job=\"airgradient-livingroom\"}",
     "legendFormat": "Humidity"
    }
   ]
  }
 ]
}